# 《利用Python进行数据分析》1st Edition chapter 7

In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

## 数据库风格的DataFrame 合并

In [2]:
df1 = DataFrame({'key':['b','b','a','c','a','a','b'], 'data1':np.arange(7)})
df2 = DataFrame({'key':['a','b','c'], 'data2':np.arange(3)})

In [3]:
df1

data1 key
0      0   b
1      1   b
2      2   a
3      3   c
4      4   a
5      5   a
6      6   b

In [4]:
df2

data2 key
0      0   a
1      1   b
2      2   c

In [5]:
pd.merge(df1, df2)

data1 key  data2
0      0   b      1
1      1   b      1
2      6   b      1
3      2   a      0
4      4   a      0
5      5   a      0
6      3   c      2

显式指定合并时用于连接的列， merge默认将重叠列的列名当做键

In [6]:
pd.merge(df1, df2, on='key')

data1 key  data2
0      0   b      1
1      1   b      1
2      6   b      1
3      2   a      0
4      4   a      0
5      5   a      0
6      3   c      2

merge默认是作 "inner"连接

In [7]:
df3 = DataFrame({'lkey':['b','b','a','c','a','a','b'], 'data1':np.arange(7)})
df4 = DataFrame({'rkey':['a','b','d'], 'data2':np.arange(3)})

In [8]:
pd.merge(df3, df4, left_on='lkey', right_on='rkey')

data1 lkey  data2 rkey
0      0    b      1    b
1      1    b      1    b
2      6    b      1    b
3      2    a      0    a
4      4    a      0    a
5      5    a      0    a

In [9]:
df3

data1 lkey
0      0    b
1      1    b
2      2    a
3      3    c
4      4    a
5      5    a
6      6    b

In [10]:
df4

data2 rkey
0      0    a
1      1    b
2      2    d

指定使用外连接

In [11]:
pd.merge(df1, df2, how='outer')

data1 key  data2
0      0   b      1
1      1   b      1
2      6   b      1
3      2   a      0
4      4   a      0
5      5   a      0
6      3   c      2

In [12]:
pd.merge(df1, df2, on= 'key', how='left')

data1 key  data2
0      0   b      1
1      1   b      1
2      2   a      0
3      3   c      2
4      4   a      0
5      5   a      0
6      6   b      1

In [13]:
df5 = DataFrame({'key':['b','b','a','c','a','b'], 'data1':np.arange(6)})
df6 = DataFrame({'key':['a','b','a','b','d'], 'data2':np.arange(5)})

In [14]:
df5

data1 key
0      0   b
1      1   b
2      2   a
3      3   c
4      4   a
5      5   b

In [15]:
df6

data2 key
0      0   a
1      1   b
2      2   a
3      3   b
4      4   d

In [16]:
pd.merge(df5, df6, on= 'key', how='left')

data1 key  data2
0       0   b    1.0
1       0   b    3.0
2       1   b    1.0
3       1   b    3.0
4       2   a    0.0
5       2   a    2.0
6       3   c    NaN
7       4   a    0.0
8       4   a    2.0
9       5   b    1.0
10      5   b    3.0

In [17]:
pd.merge(df5, df6, on= 'key', how='inner')

data1 key  data2
0      0   b      1
1      0   b      3
2      1   b      1
3      1   b      3
4      5   b      1
5      5   b      3
6      2   a      0
7      2   a      2
8      4   a      0
9      4   a      2

In [18]:
left = DataFrame({'key1': ['foo', 'foo', 'bar'],
                  'key2': ['one', 'two', 'one'],
                  'lval': [1, 2, 3]})
right = DataFrame({'key1': ['foo', 'foo', 'bar', 'bar'],
                   'key2': ['one', 'one', 'one', 'two'],
                   'rval': [4, 5, 6, 7]})
pd.merge(left, right, on=['key1', 'key2'], how='outer')

key1 key2  lval  rval
0  foo  one   1.0   4.0
1  foo  one   1.0   5.0
2  foo  two   2.0   NaN
3  bar  one   3.0   6.0
4  bar  two   NaN   7.0

In [19]:
pd.merge(left, right, on='key1')

key1 key2_x  lval key2_y  rval
0  foo    one     1    one     4
1  foo    one     1    one     5
2  foo    two     2    one     4
3  foo    two     2    one     5
4  bar    one     3    one     6
5  bar    one     3    two     7

处理列名重复问题，使用 suffixes 选项

In [20]:
pd.merge(left, right, on='key1', suffixes=('_left', '_right'))

key1 key2_left  lval key2_right  rval
0  foo       one     1        one     4
1  foo       one     1        one     5
2  foo       two     2        one     4
3  foo       two     2        one     5
4  bar       one     3        one     6
5  bar       one     3        two     7

显然，没有prefixes 选项

In [21]:
pd.merge(left, right, on='key1', prefixes=('left_', 'right_'))

TypeError: merge() got an unexpected keyword argument 'prefixes'

## 索引上的合并

In [23]:
left1 = DataFrame({'key': ['a', 'b', 'a', 'a', 'b', 'c'],
                  'value': np.arange(6)})
right1 = DataFrame({'group_val': [3.5, 7]}, index=['a', 'b'])

In [24]:
left1

key  value
0   a      0
1   b      1
2   a      2
3   a      3
4   b      4
5   c      5

In [25]:
right1

group_val
a        3.5
b        7.0

In [26]:
pd.merge(left1, right1, left_on='key', right_index=True)

key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0

In [27]:
pd.merge(left1, right1, left_on='key', right_on='group_val')

ValueError: You are trying to merge on object and float64 columns. If you wish to proceed you should use pd.concat

默认的merge方法是求取连接键的交集，若想获取并集，则应使用外连接的方式

In [28]:
pd.merge(left1, right1, left_on='key', right_index=True, how='outer')

key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0
5   c      5        NaN

In [30]:
lefth = DataFrame({'key1': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
                   'key2': [2000, 2001, 2002, 2001, 2002],
                   'data': np.arange(5.)})
righth = DataFrame(np.arange(12).reshape((6, 2)),
                   index=[['Nevada', 'Nevada', 'Ohio', 'Ohio', 'Ohio', 'Ohio'],
                          [2001, 2000, 2000, 2000, 2001, 2002]],
                   columns=['event1', 'event2'])

In [31]:
lefth

data    key1  key2
0   0.0    Ohio  2000
1   1.0    Ohio  2001
2   2.0    Ohio  2002
3   3.0  Nevada  2001
4   4.0  Nevada  2002

In [32]:
lefth=DataFrame({'key1': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
                   'key2': [2000, 2001, 2002, 2001, 2002],
                   'data': np.arange(5.)}, columns=['key1', 'key2', 'data'])
lefth

key1  key2  data
0    Ohio  2000   0.0
1    Ohio  2001   1.0
2    Ohio  2002   2.0
3  Nevada  2001   3.0
4  Nevada  2002   4.0

In [33]:
righth

event1  event2
Nevada 2001       0       1
       2000       2       3
Ohio   2000       4       5
       2000       6       7
       2001       8       9
       2002      10      11

In [34]:
# 使用lefth的 key列表 和 righth 的索引列 进行连接

In [35]:
pd.merge(lefth, righth, left_on=['key1', 'key2'], right_index=True)

key1  key2  data  event1  event2
0    Ohio  2000   0.0       4       5
0    Ohio  2000   0.0       6       7
1    Ohio  2001   1.0       8       9
2    Ohio  2002   2.0      10      11
3  Nevada  2001   3.0       0       1

In [36]:
pd.merge(lefth, righth, left_on=['key1', 'key2'], right_index=True, how='outer')

key1  key2  data  event1  event2
0    Ohio  2000   0.0     4.0     5.0
0    Ohio  2000   0.0     6.0     7.0
1    Ohio  2001   1.0     8.0     9.0
2    Ohio  2002   2.0    10.0    11.0
3  Nevada  2001   3.0     0.0     1.0
4  Nevada  2002   4.0     NaN     NaN
4  Nevada  2000   NaN     2.0     3.0

In [37]:
left2 = DataFrame([[1., 2.], [3., 4.], [5., 6.]], index=['a', 'c', 'e'],
                 columns=['Ohio', 'Nevada'])
right2 = DataFrame([[7., 8.], [9., 10.], [11., 12.], [13, 14]],
                   index=['b', 'c', 'd', 'e'], columns=['Missouri', 'Alabama'])

In [38]:
left2

Ohio  Nevada
a   1.0     2.0
c   3.0     4.0
e   5.0     6.0

In [39]:
right2

Missouri  Alabama
b       7.0      8.0
c       9.0     10.0
d      11.0     12.0
e      13.0     14.0

In [40]:
pd.merge(left2, right2, left_index=True, right_index=True, how='outer')

Ohio  Nevada  Missouri  Alabama
a   1.0     2.0       NaN      NaN
b   NaN     NaN       7.0      8.0
c   3.0     4.0       9.0     10.0
d   NaN     NaN      11.0     12.0
e   5.0     6.0      13.0     14.0

In [41]:
left2.join(right2, how='outer')

Ohio  Nevada  Missouri  Alabama
a   1.0     2.0       NaN      NaN
b   NaN     NaN       7.0      8.0
c   3.0     4.0       9.0     10.0
d   NaN     NaN      11.0     12.0
e   5.0     6.0      13.0     14.0

## 轴向连接

In [42]:
arr = np.arange(12).reshape((3, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [43]:
np.concatenate([arr, arr], axis=1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [44]:
np.concatenate([arr, arr], axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [45]:
s1 = Series([0, 1], index=['a', 'b'])
s2 = Series([2, 3, 4], index=['c', 'd', 'e'])
s3 = Series([5, 6], index=['f', 'g'])

In [46]:
pd.concat([s1, s2, s3])

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: int64

In [47]:
pd.concat([s1, s2, s3], axis=1)

D:\Anaconda\folder\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


0    1    2
a  0.0  NaN  NaN
b  1.0  NaN  NaN
c  NaN  2.0  NaN
d  NaN  3.0  NaN
e  NaN  4.0  NaN
f  NaN  NaN  5.0
g  NaN  NaN  6.0

In [49]:
s4 = pd.concat([s1 *5, s3])
s4

a    0
b    5
f    5
g    6
dtype: int64

In [50]:
pd.concat([s1, s4], axis=1)

D:\Anaconda\folder\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


0  1
a  0.0  0
b  1.0  5
f  NaN  5
g  NaN  6

In [51]:
pd.concat([s1, s4], axis=1, sort='True')

0  1
a  0.0  0
b  1.0  5
f  NaN  5
g  NaN  6

In [52]:
pd.concat([s1, s4], axis=1, join='inner', sort=True)

0  1
a  0  0
b  1  5

In [53]:
s4

a    0
b    5
f    5
g    6
dtype: int64

In [54]:
s1

a    0
b    1
dtype: int64

In [57]:
pd.concat([s1, s4], axis=1, join_axes=[['a', 'c', 'b', 'e', 'g']])

0    1
a  0.0  0.0
c  NaN  NaN
b  1.0  5.0
e  NaN  NaN
g  NaN  6.0

In [58]:
result = pd.concat([s1, s1, s3], keys=['one', 'two', 'three'])      #keys 为层次化索引

In [59]:
result

one    a    0
       b    1
two    a    0
       b    1
three  f    5
       g    6
dtype: int64

In [60]:
result.unstack()

a    b    f    g
one    0.0  1.0  NaN  NaN
two    0.0  1.0  NaN  NaN
three  NaN  NaN  5.0  6.0

In [61]:
result = pd.concat([s1, s1, s3], axis=1, keys=['one', 'two', 'three']) #指定合并方向为 axis=1, keys将成为列名
result

D:\Anaconda\folder\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


one  two  three
a  0.0  0.0    NaN
b  1.0  1.0    NaN
f  NaN  NaN    5.0
g  NaN  NaN    6.0

In [63]:
df1 = DataFrame(np.arange(6).reshape(3, 2), index=['a', 'b', 'c'],
                columns=['one', 'two'])
df2 = DataFrame(5 + np.arange(4).reshape(2, 2), index=['a', 'c'],
                columns=['three', 'four'])
pd.concat([df1, df2], axis=1, keys=['level1', 'level2'], sort=True)

level1     level2     
     one two  three four
a      0   1    5.0  6.0
b      2   3    NaN  NaN
c      4   5    7.0  8.0

In [64]:
df1

one  two
a    0    1
b    2    3
c    4    5

In [65]:
df2

three  four
a      5     6
c      7     8

In [66]:
pd.concat([df1, df2], keys=['level1', 'level2'], sort=True)

four  one  three  two
level1 a   NaN  0.0    NaN  1.0
       b   NaN  2.0    NaN  3.0
       c   NaN  4.0    NaN  5.0
level2 a   6.0  NaN    5.0  NaN
       c   8.0  NaN    7.0  NaN

In [67]:
pd.concat({'level1' : df1, 'level2' : df2}, axis=1)

D:\Anaconda\folder\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


level1     level2     
     one two  three four
a      0   1    5.0  6.0
b      2   3    NaN  NaN
c      4   5    7.0  8.0

In [68]:
pd.concat({'level1' : df1, 'level2' : df2}, axis=1, names=['upper', 'lower'], sort=True)

upper level1     level2     
lower    one two  three four
a          0   1    5.0  6.0
b          2   3    NaN  NaN
c          4   5    7.0  8.0

In [69]:
df1 = DataFrame(np.random.randn(3, 4), columns=['a', 'b', 'c', 'd'])
df2 = DataFrame(np.random.randn(2, 3), columns=['b', 'd', 'a'])

In [70]:
df1

a         b         c         d
0 -0.587884 -1.031500 -0.986180  0.957266
1 -0.372914 -0.922568 -0.825589 -1.254290
2  0.482149 -1.505038  0.024447 -1.260464

In [71]:
df2

b         d         a
0 -0.183636 -0.194122 -1.330995
1 -2.456328  0.961604 -0.114910

In [73]:
pd.concat([df1, df2], axis=1, ignore_index=True)

0         1         2         3         4         5         6
0 -0.587884 -1.031500 -0.986180  0.957266 -0.183636 -0.194122 -1.330995
1 -0.372914 -0.922568 -0.825589 -1.254290 -2.456328  0.961604 -0.114910
2  0.482149 -1.505038  0.024447 -1.260464       NaN       NaN       NaN

In [74]:
pd.concat([df1, df2], ignore_index=True)

D:\Anaconda\folder\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


a         b         c         d
0 -0.587884 -1.031500 -0.986180  0.957266
1 -0.372914 -0.922568 -0.825589 -1.254290
2  0.482149 -1.505038  0.024447 -1.260464
3 -1.330995 -0.183636       NaN -0.194122
4 -0.114910 -2.456328       NaN  0.961604

## 合并重叠数据

In [75]:
a = Series([np.nan, 2.5, np.nan, 3.5, 4.5, np.nan], index=['f','e','d','c','b','a'])
b = Series(np.arange(len(a), dtype=np.float64), index=['f','e','d','c','b','a'])

In [76]:
b

f    0.0
e    1.0
d    2.0
c    3.0
b    4.0
a    5.0
dtype: float64

In [77]:
b[-1] = np.nan

In [78]:
np.where(pd.isnull(a), b, a):
df1 = DataFrame({'a': [1., np.nan, 5., np.nan],
                 'b': [np.nan, 2., np.nan, 6.],
                 'c': range(2, 18, 4)})
df2 = DataFrame({'a': [5., 4., np.nan, 3., 7.],
                 'b': [np.nan, 3., 4., 6., 8.]})

array([0. , 2.5, 2. , 3.5, 4.5, nan])

In [79]:
b[:-2]

f    0.0
e    1.0
d    2.0
c    3.0
dtype: float64

In [80]:
a[2:]

d    NaN
c    3.5
b    4.5
a    NaN
dtype: float64

In [81]:
b[:-2].combine_first(a[2:])

a    NaN
b    4.5
c    3.0
d    2.0
e    1.0
f    0.0
dtype: float64

In [82]:
df1 = DataFrame({'a': [1., np.nan, 5., np.nan],
                 'b': [np.nan, 2., np.nan, 6.],
                 'c': range(2, 18, 4)})
df2 = DataFrame({'a': [5., 4., np.nan, 3., 7.],
                 'b': [np.nan, 3., 4., 6., 8.]})

In [83]:
df1

a    b   c
0  1.0  NaN   2
1  NaN  2.0   6
2  5.0  NaN  10
3  NaN  6.0  14

In [84]:
df2

a    b
0  5.0  NaN
1  4.0  3.0
2  NaN  4.0
3  3.0  6.0
4  7.0  8.0

In [85]:
df1.combine_first(df2)

a    b     c
0  1.0  NaN   2.0
1  4.0  2.0   6.0
2  5.0  4.0  10.0
3  3.0  6.0  14.0
4  7.0  8.0   NaN

## 重塑和轴向旋转

stack 将数据的列旋转为行， unstack 将数据的行旋转为列

In [86]:
data = DataFrame(np.arange(6).reshape((2, 3)),
                 index=pd.Index(['Ohio', 'Colorado'], name='state'),
                 columns=pd.Index(['one', 'two', 'three'], name='number'))
data

number    one  two  three
state                    
Ohio        0    1      2
Colorado    3    4      5

In [87]:
result = data.stack()
result 
type(result)

pandas.core.series.Series

In [88]:
result

state     number
Ohio      one       0
          two       1
          three     2
Colorado  one       3
          two       4
          three     5
dtype: int32

In [89]:
result.unstack()

number    one  two  three
state                    
Ohio        0    1      2
Colorado    3    4      5

In [90]:
result.unstack(0)

state   Ohio  Colorado
number                
one        0         3
two        1         4
three      2         5

In [91]:
result

state     number
Ohio      one       0
          two       1
          three     2
Colorado  one       3
          two       4
          three     5
dtype: int32

In [92]:
result.unstack('state')

state   Ohio  Colorado
number                
one        0         3
two        1         4
three      2         5

In [93]:
result.unstack('number')

number    one  two  three
state                    
Ohio        0    1      2
Colorado    3    4      5

In [94]:
s1 = Series([0, 1, 2, 3], index=['a', 'b', 'c', 'd'])
s2 = Series([4, 5, 6], index=['c', 'd', 'e'])
data2 = pd.concat([s1, s2], keys=['one', 'two'])
data2

one  a    0
     b    1
     c    2
     d    3
two  c    4
     d    5
     e    6
dtype: int64

In [95]:
data2.unstack()

a    b    c    d    e
one  0.0  1.0  2.0  3.0  NaN
two  NaN  NaN  4.0  5.0  6.0

In [96]:
data2.unstack().stack()

one  a    0.0
     b    1.0
     c    2.0
     d    3.0
two  c    4.0
     d    5.0
     e    6.0
dtype: float64

In [97]:
data2.unstack().stack(dropna=False)    #stack默认会过滤缺失数据

one  a    0.0
     b    1.0
     c    2.0
     d    3.0
     e    NaN
two  a    NaN
     b    NaN
     c    4.0
     d    5.0
     e    6.0
dtype: float64

In [98]:
df = DataFrame({'left': result, 'right': result + 5},
               columns=pd.Index(['left', 'right'], name='side'))
df

side             left  right
state    number             
Ohio     one        0      5
         two        1      6
         three      2      7
Colorado one        3      8
         two        4      9
         three      5     10

In [99]:
df.unstack('state')

side   left          right         
state  Ohio Colorado  Ohio Colorado
number                             
one       0        3     5        8
two       1        4     6        9
three     2        5     7       10

In [100]:
 df.unstack('number')

side     left           right          
number    one two three   one two three
state                                  
Ohio        0   1     2     5   6     7
Colorado    3   4     5     8   9    10

In [101]:
df.unstack('state').stack('side')

state         Colorado  Ohio
number side                 
one    left          3     0
       right         8     5
two    left          4     1
       right         9     6
three  left          5     2
       right        10     7

## 将长格式旋转为宽格式

In [110]:
data = pd.read_csv('G:/dataAnalysis/data/macrodata.csv')
periods = pd.PeriodIndex(year=data.year, quarter=data.quarter, name='date')
data = DataFrame(data.to_records(),
                 columns=pd.Index(['realgdp', 'infl', 'cpi', 'unemp', 'pop'], name='item'),
                 index=periods.to_timestamp('D', 's'))

In [111]:
data

item          realgdp  infl      cpi  unemp      pop
date                                                
1959-01-01   2710.349  0.00   28.980    5.8  177.146
1959-04-01   2778.801  2.34   29.150    5.1  177.830
1959-07-01   2775.488  2.74   29.350    5.3  178.657
1959-10-01   2785.204  0.27   29.370    5.6  179.386
1960-01-01   2847.699  2.31   29.540    5.2  180.007
1960-04-01   2834.390  0.14   29.550    5.2  180.671
1960-07-01   2839.022  2.70   29.750    5.6  181.528
1960-10-01   2802.616  1.21   29.840    6.3  182.287
1961-01-01   2819.264 -0.40   29.810    6.8  182.992
1961-04-01   2872.005  1.47   29.920    7.0  183.691
1961-07-01   2918.419  0.80   29.980    6.8  184.524
1961-10-01   2977.830  0.80   30.040    6.2  185.242
1962-01-01   3031.241  2.26   30.210    5.6  185.874
1962-04-01   3064.709  0.13   30.220    5.5  186.538
1962-07-01   3093.047  2.11   30.380    5.6  187.323
1962-10-01   3100.563  0.79   30.440    5.5  188.013
1963-01-01   3141.087  0.53   30.480    5.8  188.580
1963-04-01   3180.447  2.75   30.690    5.7  189.242
1963-07-01   3240.332  0.78   30.750    5.5  190.028
1963-10-01   3264.967  2.46   30.940    5.6  190.668
1964-01-01   3338.246  0.13   30.950    5.5  191.245
1964-04-01   3376.587  0.90   31.020    5.2  191.889
1964-07-01   3422.469  1.29   31.120    5.0  192.631
1964-10-01   3431.957  2.05   31.280    5.0  193.223
1965-01-01   3516.251  1.28   31.380    4.9  193.709
1965-04-01   3563.960  2.54   31.580    4.7  194.303
1965-07-01   3636.285  0.89   31.650    4.4  194.997
1965-10-01   3724.014  2.90   31.880    4.1  195.539
1966-01-01   3815.423  4.99   32.280    3.9  195.999
1966-04-01   3828.124  2.10   32.450    3.8  196.560
...               ...   ...      ...    ...      ...
2002-04-01  11538.770  1.56  180.000    5.8  288.028
2002-07-01  11596.430  2.66  181.200    5.7  288.783
2002-10-01  11598.824  3.08  182.600    5.8  289.421
2003-01-01  11645.819  1.31  183.200    5.9  290.019
2003-04-01  11738.706  1.09  183.700    6.2  290.704
2003-07-01  11935.461  2.60  184.900    6.1  291.449
2003-10-01  12042.817  3.02  186.300    5.8  292.057
2004-01-01  12127.623  2.35  187.400    5.7  292.635
2004-04-01  12213.818  3.61  189.100    5.6  293.310
2004-07-01  12303.533  3.58  190.800    5.4  294.066
2004-10-01  12410.282  2.09  191.800    5.4  294.741
2005-01-01  12534.113  4.15  193.800    5.3  295.308
2005-04-01  12587.535  1.85  194.700    5.1  295.994
2005-07-01  12683.153  9.14  199.200    5.0  296.770
2005-10-01  12748.699  0.40  199.400    4.9  297.435
2006-01-01  12915.938  2.60  200.700    4.7  298.061
2006-04-01  12962.462  3.97  202.700    4.7  298.766
2006-07-01  12965.916 -1.58  201.900    4.7  299.593
2006-10-01  13060.679  3.30  203.574    4.4  300.320
2007-01-01  13099.901  4.58  205.920    4.5  300.977
2007-04-01  13203.977  2.75  207.338    4.5  301.714
2007-07-01  13321.109  3.45  209.133    4.7  302.509
2007-10-01  13391.249  6.38  212.495    4.8  303.204
2008-01-01  13366.865  2.82  213.997    4.9  303.803
2008-04-01  13415.266  8.53  218.610    5.4  304.483
2008-07-01  13324.600 -3.16  216.889    6.0  305.270
2008-10-01  13141.920 -8.79  212.174    6.9  305.952
2009-01-01  12925.410  0.94  212.671    8.1  306.547
2009-04-01  12901.504  3.37  214.469    9.2  307.226
2009-07-01  12990.341  3.56  216.385    9.6  308.013

[203 rows x 5 columns]

In [112]:
ldata = data.stack().reset_index().rename(columns={0: 'value'})

In [113]:
ldata[:10]

date     item     value
0 1959-01-01  realgdp  2710.349
1 1959-01-01     infl     0.000
2 1959-01-01      cpi    28.980
3 1959-01-01    unemp     5.800
4 1959-01-01      pop   177.146
5 1959-04-01  realgdp  2778.801
6 1959-04-01     infl     2.340
7 1959-04-01      cpi    29.150
8 1959-04-01    unemp     5.100
9 1959-04-01      pop   177.830

In [114]:
pivoted = ldata.pivot('date', 'item', 'value')
pivoted.head()

item          cpi  infl      pop   realgdp  unemp
date                                             
1959-01-01  28.98  0.00  177.146  2710.349    5.8
1959-04-01  29.15  2.34  177.830  2778.801    5.1
1959-07-01  29.35  2.74  178.657  2775.488    5.3
1959-10-01  29.37  0.27  179.386  2785.204    5.6
1960-01-01  29.54  2.31  180.007  2847.699    5.2

In [115]:
# pivot(row_index_name, col_index_name, col_name_which_is_to_fill_in_the_DataFrame)

In [116]:
ldata['value2'] = np.random.randn(len(ldata))

In [117]:
ldata[:10]

date     item     value    value2
0 1959-01-01  realgdp  2710.349  0.972222
1 1959-01-01     infl     0.000  1.186838
2 1959-01-01      cpi    28.980  0.239858
3 1959-01-01    unemp     5.800 -0.490403
4 1959-01-01      pop   177.146  0.341270
5 1959-04-01  realgdp  2778.801  0.428698
6 1959-04-01     infl     2.340  0.181768
7 1959-04-01      cpi    29.150 -1.197701
8 1959-04-01    unemp     5.100 -0.022002
9 1959-04-01      pop   177.830  1.128641

In [119]:
pivoted = ldata.pivot('date', 'item')

In [120]:
pivoted[:10]

value                                   value2            \
item          cpi  infl      pop   realgdp unemp       cpi      infl   
date                                                                   
1959-01-01  28.98  0.00  177.146  2710.349   5.8  0.239858  1.186838   
1959-04-01  29.15  2.34  177.830  2778.801   5.1 -1.197701  0.181768   
1959-07-01  29.35  2.74  178.657  2775.488   5.3 -2.406618 -0.789186   
1959-10-01  29.37  0.27  179.386  2785.204   5.6  0.918046  0.674407   
1960-01-01  29.54  2.31  180.007  2847.699   5.2  0.664549 -0.001044   
1960-04-01  29.55  0.14  180.671  2834.390   5.2  1.528435  0.020383   
1960-07-01  29.75  2.70  181.528  2839.022   5.6 -1.268663  1.258980   
1960-10-01  29.84  1.21  182.287  2802.616   6.3  0.132913  0.593822   
1961-01-01  29.81 -0.40  182.992  2819.264   6.8 -0.274823  0.237654   
1961-04-01  29.92  1.47  183.691  2872.005   7.0 -0.282411  0.442799   

                                          
item             pop   realgdp     unemp  
date                                      
1959-01-01  0.341270  0.972222 -0.490403  
1959-04-01  1.128641  0.428698 -0.022002  
1959-07-01 -0.280813 -0.488316 -0.815075  
1959-10-01 -1.526437 -0.184592  1.293972  
1960-01-01  0.221328  1.863001 -0.091010  
1960-04-01  1.684621  0.673404  0.271721  
1960-07-01  0.312603 -1.433408  0.472050  
1960-10-01 -0.685251 -0.765034  0.720975  
1961-01-01  0.175280  0.681817 -0.546338  
1961-04-01  0.754295 -0.583967  0.403173

In [121]:
pivoted['value'][:5]

item          cpi  infl      pop   realgdp  unemp
date                                             
1959-01-01  28.98  0.00  177.146  2710.349    5.8
1959-04-01  29.15  2.34  177.830  2778.801    5.1
1959-07-01  29.35  2.74  178.657  2775.488    5.3
1959-10-01  29.37  0.27  179.386  2785.204    5.6
1960-01-01  29.54  2.31  180.007  2847.699    5.2

In [122]:
unstacked = ldata.set_index(['date', 'item']).unstack('item')    #pivot() 等同于 先 set_index() 再  unstack()

In [124]:
unstacked[:10]

value                                   value2            \
item          cpi  infl      pop   realgdp unemp       cpi      infl   
date                                                                   
1959-01-01  28.98  0.00  177.146  2710.349   5.8  0.239858  1.186838   
1959-04-01  29.15  2.34  177.830  2778.801   5.1 -1.197701  0.181768   
1959-07-01  29.35  2.74  178.657  2775.488   5.3 -2.406618 -0.789186   
1959-10-01  29.37  0.27  179.386  2785.204   5.6  0.918046  0.674407   
1960-01-01  29.54  2.31  180.007  2847.699   5.2  0.664549 -0.001044   
1960-04-01  29.55  0.14  180.671  2834.390   5.2  1.528435  0.020383   
1960-07-01  29.75  2.70  181.528  2839.022   5.6 -1.268663  1.258980   
1960-10-01  29.84  1.21  182.287  2802.616   6.3  0.132913  0.593822   
1961-01-01  29.81 -0.40  182.992  2819.264   6.8 -0.274823  0.237654   
1961-04-01  29.92  1.47  183.691  2872.005   7.0 -0.282411  0.442799   

                                          
item             pop   realgdp     unemp  
date                                      
1959-01-01  0.341270  0.972222 -0.490403  
1959-04-01  1.128641  0.428698 -0.022002  
1959-07-01 -0.280813 -0.488316 -0.815075  
1959-10-01 -1.526437 -0.184592  1.293972  
1960-01-01  0.221328  1.863001 -0.091010  
1960-04-01  1.684621  0.673404  0.271721  
1960-07-01  0.312603 -1.433408  0.472050  
1960-10-01 -0.685251 -0.765034  0.720975  
1961-01-01  0.175280  0.681817 -0.546338  
1961-04-01  0.754295 -0.583967  0.403173

## 数据转换

In [125]:
data = DataFrame({'k1': ['one'] * 3 + ['two'] * 4,
                  'k2': [1, 1, 2, 3, 3, 4, 4]})
data

k1  k2
0  one   1
1  one   1
2  one   2
3  two   3
4  two   3
5  two   4
6  two   4

In [126]:
data.duplicated()

0    False
1     True
2    False
3    False
4     True
5    False
6     True
dtype: bool

In [128]:
data.drop_duplicates()

k1  k2
0  one   1
2  one   2
3  two   3
5  two   4

In [129]:
data['v1'] = np.arange(7)
data

k1  k2  v1
0  one   1   0
1  one   1   1
2  one   2   2
3  two   3   3
4  two   3   4
5  two   4   5
6  two   4   6

In [130]:
data.drop_duplicates(['k1'])

k1  k2  v1
0  one   1   0
3  two   3   3

In [131]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
dtype: bool

In [132]:
data

k1  k2  v1
0  one   1   0
1  one   1   1
2  one   2   2
3  two   3   3
4  two   3   4
5  two   4   5
6  two   4   6

In [134]:
data.drop_duplicates(['k1', 'k2'], take_last=True)

TypeError: drop_duplicates() got an unexpected keyword argument 'take_last'

In [135]:
data.drop_duplicates(['k1', 'k2'], keep='last')

k1  k2  v1
1  one   1   1
2  one   2   2
4  two   3   4
6  two   4   6

## 利用函数或映射进行数据转换

In [136]:
data = DataFrame({'food': ['bacon', 'pulled pork', 'bacon', 'Pastrami',
                           'corned beef', 'Bacon', 'pastrami', 'honey ham',
                           'nova lox'],
                  'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

map() 方法接受一个函数或者含有映射关系的字典型对象

In [138]:
meat_to_animal = {
  'bacon': 'pig',
  'pulled pork': 'pig',
  'pastrami': 'cow',
  'corned beef': 'cow',
  'honey ham': 'pig',
  'nova lox': 'salmon'
}
data['animal'] = data['food'].map(str.lower).map(meat_to_animal)

In [139]:
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [141]:
data['animal'] = data['food'].map(lambda x : meat_to_animal[x.lower()])
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

## 离散化和面元划分

In [142]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 62, 45, 43, 32]
bins = [18, 25, 35, 60 ,100]
cats = pd.cut(ages, bins)
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [143]:
type(cats)

pandas.core.arrays.categorical.Categorical

In [145]:
cats.labels

AttributeError: 'Categorical' object has no attribute 'labels'

In [148]:
# 上述异常表明属性名称的更新  categories 替换levels
cats.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]],
              closed='right',
              dtype='interval[int64]')

In [150]:
cats.codes     # codes 替换 labels

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [151]:
pd.value_counts(cats)

(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64

In [153]:
# 自己设置面元名称
group_names = ['Youth', 'YoungAdult', 'MiddleAged', 'Senior']
pd.cut(ages, bins, labels=group_names)

[Youth, Youth, Youth, YoungAdult, Youth, ..., YoungAdult, Senior, MiddleAged, MiddleAged, YoungAdult]
Length: 12
Categories (4, object): [Youth < YoungAdult < MiddleAged < Senior]

In [154]:
data = np.random.rand(20)

In [155]:
data

array([0.37118803, 0.82008086, 0.9466561 , 0.07788135, 0.08052459,
       0.80295939, 0.9760262 , 0.85214839, 0.70822476, 0.50862838,
       0.03144178, 0.8743571 , 0.38073654, 0.53689538, 0.04678199,
       0.01659403, 0.29027677, 0.21144076, 0.99355481, 0.44978547])

In [156]:
pd.cut(data, 4, precision=2)     #传入面元数量则根据数据的最小和最大值等值计算等长面元

[(0.26, 0.51], (0.75, 0.99], (0.75, 0.99], (0.016, 0.26], (0.016, 0.26], ..., (0.016, 0.26], (0.26, 0.51], (0.016, 0.26], (0.75, 0.99], (0.26, 0.51]]
Length: 20
Categories (4, interval[float64]): [(0.016, 0.26] < (0.26, 0.51] < (0.51, 0.75] < (0.75, 0.99]]

In [157]:
data = np.random.rand(1000)
data

array([5.17401264e-02, 2.09158471e-02, 3.36291923e-01, 4.03066209e-01,
       6.00141291e-01, 9.72825970e-01, 2.21063004e-01, 9.80717026e-01,
       3.20696971e-02, 3.09617303e-03, 7.14525392e-01, 6.60695500e-01,
       2.15268630e-02, 9.34016560e-01, 5.29886465e-02, 5.32299903e-01,
       7.69561614e-01, 5.87246890e-01, 4.46202875e-01, 1.88702883e-02,
       9.18325581e-01, 1.90508672e-01, 7.96404977e-01, 7.66038921e-01,
       7.93723166e-01, 4.91676057e-01, 9.72087310e-01, 2.63645094e-01,
       6.32376148e-01, 4.40756382e-02, 2.65400821e-01, 7.74698414e-01,
       2.14734032e-01, 3.94992104e-01, 8.11209247e-01, 4.77975865e-01,
       8.10760375e-01, 7.48351338e-02, 3.27439949e-01, 8.31485801e-01,
       4.51986880e-01, 7.47971298e-01, 1.57410148e-01, 5.75044959e-01,
       6.11076340e-01, 6.25306434e-01, 3.77154740e-01, 3.75142632e-01,
       7.79644628e-01, 9.97814088e-01, 2.95413255e-01, 6.26749116e-01,
       8.29792346e-01, 1.05814665e-01, 4.30425168e-01, 1.57888543e-01,
      

In [158]:
cats = pd.qcut(data, 4)
cats

[(-0.000894, 0.254], (-0.000894, 0.254], (0.254, 0.507], (0.254, 0.507], (0.507, 0.764], ..., (0.507, 0.764], (0.254, 0.507], (-0.000894, 0.254], (0.507, 0.764], (-0.000894, 0.254]]
Length: 1000
Categories (4, interval[float64]): [(-0.000894, 0.254] < (0.254, 0.507] < (0.507, 0.764] < (0.764, 0.999]]

In [159]:
pd.value_counts(cats)     # 使用qcut() 可以得到大小基本相等的面元

(0.764, 0.999]        250
(0.507, 0.764]        250
(0.254, 0.507]        250
(-0.000894, 0.254]    250
dtype: int64